# Generated by Django 6.0.2 on 2026-05-07 11:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('type_article', models.CharField(choices=[('Matière Première', 'Matière Première'), ('Produit Fini', 'Produit Fini')], max_length=32)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('stock_min', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_exp', models.CharField(max_length=64, unique=True)),
                ('date_exp', models.DateField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.client')),
            ],
        ),
        migrations.CreateModel(
            name='ConcerneExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.article')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='supplychain.expedition')),
            ],
        ),
        migrations.CreateModel(
            name='OrdreFabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of', models.CharField(max_length=64, unique=True)),
                ('qte_prevue', models.IntegerField()),
                ('qte_produite', models.IntegerField(default=0)),
                ('date_prevue', models.DateField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé')], default='En attente', max_length=20)),
                ('num_lot', models.CharField(blank=True, max_length=64)),
                ('article_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofs', to='supplychain.article')),
            ],
        ),
        migrations.CreateModel(
            name='Consomme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_consommee', models.IntegerField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.article')),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.ordrefabrication')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_rec', models.CharField(max_length=64, unique=True)),
                ('date_rec', models.DateField(default=django.utils.timezone.now)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mvt', models.CharField(max_length=64)),
                ('qte', models.IntegerField()),
                ('date_mvt', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.article')),
                ('exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplychain.expedition')),
                ('of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplychain.ordrefabrication')),
                ('rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplychain.reception')),
            ],
        ),
        migrations.CreateModel(
            name='ConcerneRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.article')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='supplychain.reception')),
            ],
        ),
    ]
